### ISSUE TITLE
WSO2 error "Provided Authorization Grant is invalid"

### ISSUE THREAD

**Issue by pashtika** [wso2/product-private-paas#67]
I am sending SAMLAssertion to WSO2 IDP (Identity Provider) and it's giving me following error. I've retrieved SAMLAssertion from SAMLResponse and sending it ahead to IDP
What could be the reason of
{"error":"invalid_grant","error_description":"Provided Authorization Grant is invalid."}

ERROR {org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler} -  Error in constructing XML Object from the encoded String {org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler}
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

**Comment by sajhak** [comment]
@pashtika, could you please elaborate more on this issue? In which component you are getting this issue? (Cloud controller, autoscaler.. etc? ) Also, during when you are getting this issue? Is it when partition deployment? or subscription?

**Comment by pashtika** [comment]
I am sending the SAMLAssertion to send to WSO2 IDP.

**Comment by imesh** [comment]
It looks like there is an XML parse error on the WSO2 IS side. Are you making a call to WSO2 IS to obtain an OAuth token with SAML grant type? May be you have not properly encoded the SAML Assertion with Base64 and URL encoding.

**Comment by pashtika** [comment]
I'm developing IDP initiated SAML where I'm login into IDP (WSO2 IS) server which is giving back me <SAMLResponse>, now from  <SAMLResponse> I'm retrieving <SAMLAssertion> by using Open SAML library and trying to send it further to WSO2 and facing above mentioned error

**Comment by imesh** [comment]
Right, I guess this discussion is on the place. May be you could move this to WSO2 Dev mailing list and send more details (wso2carbon.log of WSO2 IS, SAML Assertion being sent, etc) about the scenario.
